add session1
Zarebin/internship-4-js-notes pull request #14
Opened 2022-07-24 19:00 UTC by Tahoora78

add session1

2022-07-24 22:43 UTC, M-Heidari2000 commented on session1(1401-05-2).md
> +- ctrl + r ---> reverse searching smong entered commands
among

2022-07-24 22:43 UTC, M-Heidari2000 commented on session1(1401-05-2).md
> +-   The difinnitive guide js david flanagan
definitive

2022-07-24 22:50 UTC, M-Heidari2000 commented on session1(1401-05-2).md
> +### deletting a  branch
deleting

2022-07-24 22:56 UTC, M-Heidari2000 requested changes
Perfect! except for a couple of typos. I've added comments on those lines.

2022-07-25 04:20 UTC, Tahoora78 commented
I resolved the typos

2022-07-25 05:05 UTC, lashkariam approved these changes

2022-07-25 06:40 UTC, M-Heidari2000 approved these changes

2022-07-25 07:45 UTC, amin-rami approved these changes

2022-07-25 07:46 UTC, amin-rami approved these changes

2022-07-25 07:46 UTC, merged